#! /bin/bash

PATH_OF_SCRIPT="$(realpath "$0")"
PATH_OF_SCRIPT_FOLDER="$(dirname "$PATH_OF_SCRIPT")"
if [$# -lt 4] then
    python3 $PATH_OF_SCRIPT_FOLDER/apply_model.py $1 $2
else
    python3 $PATH_OF_SCRIPT_FOLDER/apply_model.py $1 $2 $3
fi

