#! /bin/bash

PATH_OF_THIS_SCRIPT="$(realpath "$0")"
PATH_OF_THIS_SCRIPT_FOLDER="$(dirname "$PATH_OF_THIS_SCRIPT")"
#python3 $PATH_OF_THIS_SCRIPT_FOLDER/train_model.py $1 $2
bsub -o $2-testing-stdout.txt -e $2-testing-stderr.txt -q gpu_any -n2 -gpu "num=1" singularity exec -B /scratch,/groups/svoboda/home/svobodalab/delectable --nv $PATH_OF_THIS_SCRIPT_FOLDER/dlc.simg python3 $PATH_OF_THIS_SCRIPT_FOLDER/test_model.py $1 $2
